export const USER_ACTION_TYPE = {
  SET_LOGIN_REQUEST: "user/SET_LOGIN_REQUEST",
  SET_LOGIN_SUCCESS: "user/SET_LOGIN_SUCCESS",
  SET_LOGIN_FAILED: "user/SET_LOGIN_FAILED",

  SET_SIGNOUT_REQUEST: "user/SET_SIGNOUT_REQUEST",
  SET_SIGNOUT_SUCCESS: "user/SET_SIGNOUT_SUCCESS",

  SET_SIGNUP_REQUEST: "auth/SET_SIGNUP_REQUEST",
  SET_SIGNUP_SUCCESS: "auth/SET_SIGNUP_SUCCESS",
  SET_SIGNUP_FAILED: "auth/SET_SIGNUP_FAILED",
};
