export const PRODUCT_ACTION_CONST = {
  GET_ALL_PRODUCTS_REQUEST: "product/GET_ALL_PRODUCTS_REQUEST",
  GET_ALL_PRODUCTS_SUCCESS: "product/GET_ALL_PRODUCTS_SUCCESS",
  GET_ALL_PRODUCTS_FAILURE: "product/GET_ALL_PRODUCTS_FAILURE",

  SET_ALL_PRODUCTS_REQUEST: "product/SET_ALL_PRODUCTS_REQUEST",
  SET_ALL_PRODUCTS_SUCCESS: "product/SET_ALL_PRODUCTS_SUCCESS",
  SET_ALL_PRODUCTS_FAILURE: "product/SET_ALL_PRODUCTS_FAILURE",

  ADD_PRODUCT_REQUEST: "product/ADD_PRODUCT_REQUEST",
  ADD_PRODUCT_SUCCESS: "product/ADD_PRODUCT_SUCCESS",
  ADD_PRODUCT_FAILURE: "product/ADD_PRODUCT_FAILURE",

  DELETE_PRODUCT_BY_ID_REQUEST: "product/DELETE_PRODUCT_BY_ID_REQUEST",
  DELETE_PRODUCT_BY_ID_SUCCESS: "product/DELETE_PRODUCT_BY_ID_SUCCESS",
  DELETE_PRODUCT_BY_ID_FAILURE: "product/DELETE_PRODUCT_BY_ID_FAILURE",
};
