export const CATEGORIES_ACTION_TYPE = {
  SET_CATEGORY_DATA: "categories/SET_CATEGORY_DATA",
  FETCH_CATEGORIES_SUCCESS: "categories/FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILURE: "categories/FETCH_CATEGORIES_FAILURE",
};
