export const allProducts = [
  {
    title: "Male Enhancement",
    subCategory: [
      {
        title: "Honey",
        items: [
          {
            id: 1,
            name: "Royal Honey VIP 20g Sachet",

            image: ["/Honey/Royal Honey VIP/Royal Honey VIP.jpeg"],
            offer: 10,
            unit: "12 Sachet Per Box",
            price: 31.99,
            MOQ: "96 Box",
          },
          {
            id: 2,
            name: "Royal Honey VIP 22g Pouches",

            image: ["/Honey/Royal Honey VIP/RoYAL hONEY.jpeg"],
            offer: 20,
            unit: "15 Pouches Per Box, 28 Box Per Carton",
            price: 38,
            MOQ: "280 Box",
            offer: 20,
          },
          {
            id: 3,
            name: "Etumax Honey 20g Sachet",

            image: ["/Honey/Etumax Honey/Etumax(4).jpeg"],
            offer: 20,
            unit: "12 Sachet Per Box, 60 Box Per Carton",
            price: 27,
            MOQ: "120 Box",
          },
          {
            id: 4,
            name: "Etumax Honey 22g Pouches",

            image: ["/Honey/Etumax Honey/Etumax.jpeg"],
            offer: 20,
            unit: "15 Pouches Per Box ,28 Box Per Carton",
            price: 38,
            MOQ: "280 Box",
          },
          {
            id: 5,
            name: "Black Bull Honey 22g Pouches",

            image: ["/Honey/Black Bull Honey/Black Bull Honey.jpg"],
            offer: 20,
            unit: "12 Poches Per Box, 48 Box Per Carton",
            price: 35,
            MOQ: "96 Box",
          },
          {
            id: 6,
            name: "Black Bull Honey 22g Pouches",
            image: ["/Honey/Black Bull Honey/Black Bull.jpeg"],

            offer: 20,
            unit: "15 Pouches Per Box, 28 Box Per Carton",
            price: 38,
            MOQ: "280 Box",
          },
          {
            id: 7,
            name: "Red Bull Honey 22g Pouches",

            image: ["/Honey/Red Bull Honey/Red Bull Honey.jpeg"],
            offer: 20,
            unit: "12 Poches Per Box, 40 Box Per Carton",
            price: 35,
            MOQ: "80 Box",
          },
          {
            id: 8,
            name: "Red Bull Honey 22g Pouches",

            image: ["/Honey/Red Bull Honey/Red Bull Honey.jpeg"],
            offer: 20,
            unit: "15 Pouches Per Box, 28 Box Per Carton",
            price: 38,
            MOQ: "280 Box",
          },
          {
            id: 9,
            name: "Blue Bull Honey 22g Pouches",

            image: ["/Honey/Blue Bull Honey/Blue Bull.jpeg"],
            offer: 20,
            unit: "12 Poches Per Box, 40 Box Per Carton",
            price: 35,
            MOQ: "80 Box",
          },
          {
            id: 10,
            name: "Blue Bull Honey 22g Pouches",

            image: ["/Honey/Blue Bull Honey/Blue Bull.jpeg"],
            offer: 20,
            unit: "15 Pouches Per Box, 28 Box Per Carton",
            price: 38,
            MOQ: "280 Box",
          },
          {
            id: 11,
            name: "Leopard Miracle Honey 15g Sachet",
            image: [
              "/Honey/Leopard Miracle Honey VIP/Leopard Miracle VIP.jpeg",
            ],
            offer: 20,
            unit: "12 Sachet Per Box, 40 Box Per Carton",
            price: 30,
            MOQ: "80 Box",
          },
          {
            id: 12,
            name: "Leopard Miracle Honey 22g Pouches",
            image: [
              "/Honey/Leopard Miracle Honey VIP/Leopard Miracle VIP.jpeg",
            ],
            offer: 20,
            unit: "15 Pouches Per Box, 28 Box Per Carton",
            price: 38,
            MOQ: "280 Box",
          },
          {
            id: 13,
            name: "Secret Miracle Honey 15g Sachet",
            image: ["/Honey/Secret Miracel Honey/Secret Miracel Honey.jpeg"],
            offer: 20,
            unit: "12 Poches Per Box, 40 Box Per Carton",
            price: 32,
            MOQ: "80 Box",
          },
          {
            id: 14,
            name: "Vitamax Double Shot 20g Sachet",

            image: ["/Honey/Vitamax Double shot/Vitamax Double shot.jpeg"],
            offer: 20,
            unit: "10 Poches Per Box, 48 Box Per Carton",
            price: 37,
            MOQ: "97 Box",
          },
        ],
      },
      {
        title: "Liquid Shots",
        items: [
          {
            id: 15,
            name: "Rhino 69 Liquid Shot ",
            image: [
              "/Pills/Rhino-69-1000k/Rhino-69-1000k-Front-Side.png",
              "/Pills/Rhino-69-1000k/Rhino-69-1000k-Rear-Side.png",
            ],
            offer: 20,
            unit: "12 Bottles Per Box",
            price: 40,
            MOQ: "20 Box",
          },
          {
            id: 16,
            name: "Rhino Platinum Liquid Shot",
            image: [
              "/Pills/Rhino-69-1200k/Rhino-69-1200k-Front-Side.png",
              "/Pills/Rhino-69-1200k/Rhino-69-1200k-Rear-Side.png",
            ],
            offer: 20,
            unit: "12 Bottles Per Box",
            price: 40,
            MOQ: "20 Box",
          },
          {
            id: 17,
            name: "Hard Steel Liquid Shot",
            image: [
              "/Pills/Opal-Black/Opal-Black-Front-Side.png",
              "/Pills/Opal-Black/Opal-Black-Rear-Side.png",
            ],
            offer: 20,
            unit: "12 Bottles Per Box",
            price: 40,
            MOQ: "20 Box",
          },
          {
            id: 18,
            name: "Super Man Liquid Shot",
            image: [
              "/Pills/Bullet-3000/Bullet-3000-Front-Side.png",
              "/Pills/Bullet-3000/Bullet-3000-Rear-Side.png",
            ],
            offer: 20,
            unit: "12 Bottles Per Box",
            price: 40,
            MOQ: "20 Box",
          },
        ],
      },
      {
        title: "Pills",
        items: [
          {
            id: 19,
            name: "100k Gold",
            image: [
              "/Pills/100k-Gold/100k-Gold-Front-Side.png",
              "/Pills/100k-Gold/100k-Gold-Rear-Side.png",
            ],
            offer: 20,
            unit: "1 Pcs Per Box",
            price: 250,
            MOQ: "100 Box",
          },
          {
            id: 20,
            name: "Black-Panther-350k",
            image: [
              "/Pills/Black-Panther-350k/Black-Panther-350k-Front-Side.png",
              "/Pills/Black-Panther-350k/Black-Panther-350k-Rear-Side.png",
            ],
            offer: 20,
            unit: "4 Pcs Per Box",
            price: 350,
            MOQ: "100 Box",
          },
          {
            id: 21,
            name: "Bullet-3000",
            image: [
              "/Pills/Bullet-3000/Bullet-3000-Front-Side.png",
              "/Pills/Bullet-3000/Bullet-3000-Rear-Side.png",
            ],
            offer: 20,
            unit: "30 Pcs Per Bottle",
            price: 800,
            MOQ: "100 Bottles",
          },
          {
            id: 22,
            name: "Magnum-1000k",
            image: [
              "/Pills/Magnum-1000k/Magnum-1000k-Front-Side-Double.png",
              "/Pills/Magnum-1000k/Magnum-1000k-Front-Side-Double.png",
            ],
            offer: 20,
            unit: "2 Pcs Per Box",
            price: 250,
            MOQ: "100 Box",
            offer: 20,
          },
          {
            id: 23,
            name: "Magnum-Platinum-250k",
            image: [
              "/Pills/Magnum-Platinum-250k/Magnum-Platinum-250k-Front-Side.png",
              "/Pills/Magnum-Platinum-250k/Magnum-Platinum-250k-Rear-Side.png",
            ],
            offer: 20,
            unit: "30 Pcs Per Bottle",
            price: 800,
            MOQ: "100 Bottles",
            offer: 20,
          },
          {
            id: 24,
            name: "Magnum-Gold-1000k",
            image: [
              "/Pills/Magnum-Gold-1000k/Magnum-Gold-1000k-Gold-Side.png",
              "/Pills/Magnum-Gold-1000k/Magnum-Gold-1000k-Rear-Side.png",
            ],
            offer: 20,
            unit: "30 Pcs Per Bottle",
            price: 800,
            MOQ: "100 Bottles",
            offer: 20,
          },
          {
            id: 25,
            name: "Spanish-fly-22000-Green",
            image: [
              "/Pills/Spanish-fly-22000-Green/Spanish-fly-22000-Front-Side-Green.png",
              "/Pills/Spanish-fly-22000-Green/Spanish-fly-22000-Rear-Side-Green.png",
            ],
            offer: 20,
            unit: "1 Pcs Per Bag",
            price: 500,
            MOQ: "500 Bag",
          },
          {
            id: 26,
            name: "Spanish-fly-22000-Red",
            image: [
              "/Pills/Spanish-fly-22000-Red/Spanish-fly-22000-Front-Side-Red.png",
              "/Pills/Spanish-fly-22000-Red/Spanish-fly-22000-Rear-Side Red.png",
            ],
            offer: 20,
            unit: "25 Pcs Per Pack",
            price: 900,
            MOQ: "100 Pack",
          },
          {
            id: 27,
            name: "Bullet-3000",
            image: [
              "/Pills/Bullet-3000/Bullet-3000-Front-Side.png",
              "/Pills/Bullet-3000/Bullet-3000-Rear-Side.png",
            ],
            offer: 20,
            unit: "30 Pack Per Box, 57 Box Per Carton",
            price: 500,
            MOQ: "114 Box",
          },
          {
            id: 28,
            name: "Opal-Black",
            image: [
              "/Pills/Opal-Black/Opal-Black-Front-Side.png",
              "/Pills/Opal-Black/Opal-Black-Rear-Side.png",
            ],
            offer: 20,
            unit: "30 Pack Per Box, 57 Box Per Carton",
            price: 500,
            MOQ: "114 Box",
          },
          {
            id: 29,
            name: "Zesus-250k",
            image: [
              "/Pills/Zesus-250k/Zesus-250k-Front-Side.png",
              "/Pills/Zesus-250k/Zesus-250k-Rear-Side.png",
            ],
            offer: 20,
            unit: "36 Pack Per Box, 48 Box Per Carton",
            price: 500,
            MOQ: "96 Box",
          },
          {
            id: 30,
            name: "Rhino-69-1000k",
            image: [
              "/Pills/Rhino-69-1000k/Rhino-69-1000k-Front-Side.png",
              "/Pills/Rhino-69-1000k/Rhino-69-1000k-Rear-Side.png",
            ],
            offer: 20,
            unit: "24 Pack 48 Pills Per Box",
            price: 1000,
            MOQ: "100 Box",
          },
          {
            id: 31,
            name: "Rhino-69-1200k",
            image: [
              "/Pills/Rhino-69-1200k/Rhino-69-1200k-Front-Side.png",
              "/Pills/Rhino-69-1200k/Rhino-69-1200k-Rear-Side.png",
            ],
            offer: 20,
            unit: "24 Pack 48 Pills Per Box",
            price: 1000,
            MOQ: "100 Box",
          },
          {
            id: 32,
            name: "Rhino-69-1300k",
            image: [
              "/Pills/Rhino-69-1300k/Rhino-69-1300k-Front-Side.png",
              "/Pills/Rhino-69-1300k/Rhino-69-1300k-Rear-Side.png",
            ],
            offer: 20,
            unit: "24 Pack 48 Pills Per Box",
            price: 1000,
            MOQ: "100 Box",
          },
          {
            id: 33,
            name: "Rhino-69-1300k-Double",
            image: [
              "/Pills/Rhino-69-1300k-Double/Rhino-69-1300k-Front-Side-Double.png",
              "/Pills/Rhino-69-1300k-Double/Rhino-69-1300k-Rear-Side-Double.png",
            ],
            offer: 20,
            unit: "24 Pack 24 Pills Per Box",
            price: 1000,
            MOQ: "100 Box",
          },
          {
            id: 34,
            name: "Rhino-69-1400k",
            image: [
              "/Pills/Rhino-69-1400k/Rhino-69-1400k-Front-Side.png",
              "/Pills/Rhino-69-1400k/Rhino-69-1400k-Rear-Side.png",
            ],
            offer: 20,
            unit: "24 Pack 72 Pills Per Box",
            price: 1800,
            MOQ: "100 Box",
          },
          {
            id: 35,
            name: "Rhino-69-1500k-Double",
            image: [
              "/Pills/Rhino-69-1500k-Double/Rhino-69-1500k-Front-Side-Double.png",
              "/Pills/Rhino-69-1500k-Double/Rhino-69-1500k-Rear-Side-Double.png",
            ],
            offer: 20,
            unit: "24 Pack 24 Pills Per Box, 12 Large Card+12 Small Card",
            price: 1800,
            MOQ: "100 Box",
          },
          {
            id: 36,
            name: "Rhino-69-1600k",
            image: [
              "/Pills/Rhino-69-1600k/Rhino-69-1600k-Front-Side.png",
              "/Pills/Rhino-69-1600k/Rhino-69-1600k-Rear-Side.png",
            ],
            offer: 20,
            unit: "24 Pack 24 Pills Per Box",
            price: 1800,
            MOQ: "100 Box",
          },
          {
            id: 37,
            name: "Rhino-69-1600k-Double",
            image: [
              "/Pills/Rhino-69-1600k-Double/Rhino-69-1600k-Front-Side-Double.png",
              "/Pills/Rhino-69-1600k-Double/Rhino-69-1600k-Rear-Side-Double.png",
            ],
            offer: 20,
            unit: "24 Pack 24 Pills Per Box",
            price: 1800,
            MOQ: "100 Box",
          },
          {
            id: 38,
            name: "Rhino-69-1700k-double",
            image: [
              "/Pills/Rhino-69-1700k-double/Rhino-69-1700k-Front-Side-double.png",
              "/Pills/Rhino-69-1700k-double/Rhino-69-1700k-Rear-Side-double.png",
            ],
            offer: 20,
            unit: "24 Pack 24 Pills Per Box",
            price: 1800,
            MOQ: "100 Box",
          },
          {
            id: 39,
            name: "Rhino-69-1700k-Single",
            image: [
              "/Pills/Rhino-69-1700k-Single/Rhino-69-1700k-Front-Side-Single.png",
              "/Pills/Rhino-69-1700k-Single/Rhino-69-1700k-Rear-Side-Single.png",
            ],
            offer: 20,
            unit: "24 Pack 24 Pills Per Box",
            price: 1800,
            MOQ: "100 Box",
          },
          {
            id: 40,
            name: "Rhino-69-1800k-Double",
            image: [
              "/Pills/Rhino-69-1800k-Double/Rhino-69-1800k-Front-Side-Double.png",
              "/Pills/Rhino-69-1800k-Double/Rhino-69-1800k-Rear-Side-Double.png",
            ],
            offer: 20,
            unit: "24 Pack 24 Pills Per Box",
            price: 1800,
            MOQ: "100 Box",
          },
          {
            id: 41,
            name: "Rhino-69-1900k",
            image: [
              "/Pills/Rhino-69-1900k/Rhino-69-1900k-Front-Side.png",
              "/Pills/Rhino-69-1900k/Rhino-69-1900k-Rear-Side.png",
            ],
            offer: 20,
            unit: "24 Pack 120 Pills Per Box",
            price: 1800,
            MOQ: "100 Box",
          },
          {
            id: 42,
            name: "Rhino-69-1900k-Single",
            image: [
              "/Pills/Rhino-69-1900k-Single/Rhino-69-1900k-Front-Side-Single.png",
              "/Pills/Rhino-69-1900k-Single/Rhino-69-1900k-Rear-Side-Single.png",
            ],
            offer: 20,
            unit: "24 Pack 120 Pills Per Box",
            price: 1800,
            MOQ: "100 Box",
          },
          {
            id: 43,
            name: "Rhino-69-2100k",
            image: [
              "/Pills/Rhino-69-2100k/Rhino-69-2100k-Front-Side.png",
              "/Pills/Rhino-69-2100k/Rhino-69-2100k-Rear-Side.png",
            ],
            offer: 20,
            unit: "24 Pack 120 Pills Per Box",
            price: 1800,
            MOQ: "100 Box",
          },
          {
            id: 44,
            name: "Rhino-69-2100k-Single",
            image: [
              "/Pills/Rhino-69-2100k-Single/Rhino-69-2100k-Front-Side-Single.png",
              "/Pills/Rhino-69-2100k-Single/Rhino-69-2100k-Rear-Side-Single.png",
            ],
            offer: 20,
            unit: "24 Pack 120 Pills Per Box",
            price: 1800,
            MOQ: "100 Box",
          },
          {
            id: 45,
            name: "Rhino-69-2400k-Red",
            image: [
              "/Pills/Rhino-69-2400k-Red/Rhino-69-2400k-Front-Side-Red.png",
              "/Pills/Rhino-69-2400k-Red/Rhino-69-2400k-Rear-Side-Red.png",
            ],
            offer: 20,
            unit: "24 Pack 120 Pills Per Box",
            price: 1800,
            MOQ: "100 Box",
          },
          {
            id: 46,
            name: "Rhino-69-2400k-Red-Single",
            image: [
              "/Pills/Rhino-69-2400k-Red-Single/Rhino-69-2400k-Front-Side-Red-Single.png",
              "/Pills/Rhino-69-2400k-Red-Single/Rhino-69-2400k-Rear-Side-Red-Single.png",
            ],
            offer: 20,
            unit: "24 Pack 120 Pills Per Box",
            price: 1800,
            MOQ: "100 Box",
          },
          {
            id: 47,
            name: "Rhino-69-18000-Single",
            image: [
              "/Pills/Rhino-69-18000-Single/Rhino-69-18000-Front-Side-Single.png",
              "/Pills/Rhino-69-18000-Single/Rhino-69-18000-Rear-Side-Single.png",
            ],
            offer: 20,
            unit: "24 Pack 120 Pills Per Box",
            price: 1800,
            MOQ: "100 Box",
          },
          {
            id: 48,
            name: "Premier ZEN Gold 13000 Single Pack",
            image: [
              "/Honey/Black Bull Honey/Black Bull Honey.jpg",
              "/Honey/Black Bull Honey/Black Bull.jpeg",
            ],
            offer: 20,
            unit: "24 Pack 24 Pills Per Box",
            price: 1000,
            MOQ: "100 Box",
          },
          {
            id: 49,
            name: "Premier ZEN 7000 Single Pack",
            image: ["/Honey/Blue Bull Honey/Blue Bull.jpeg"],
            offer: 20,
            unit: "24 Pack 24 Pills Per Box, 12 Large Card+12 Small Card",
            price: 1000,
            MOQ: "100 Box",
          },
          {
            id: 50,
            name: "Premier ZEN Black 5000 Single Pack",
            image: ["/Honey/Leopard Honey/Leopard MiracleHoney.jpg"],
            offer: 20,
            unit: "24 Pack 24 Pills Per Box, 12 Large Card+12 Small Card",
            price: 1000,
            MOQ: "100 Box",
          },
          {
            id: 51,
            name: "SWAG 50 Red Single Pack",
            image: [
              "/Honey/Leopard Miracle Honey VIP/Leopard Miracle VIP.jpeg",
            ],
            offer: 20,
            unit: "24 Pack 24 Pills Per Box",
            price: 1000,
            MOQ: "100 Box",
          },
          {
            id: 52,
            name: "SWAG 100K Yellow Single Pack",
            image: ["/Honey/Red Bull Honey/Red Bull Honey.jpeg"],
            offer: 20,
            unit: "24 Pack 24 Pills Per Box",
            price: 1000,
            MOQ: "100 Box",
          },
          {
            id: 53,
            name: "vROX Gold Single Pack",
            image: ["/Honey/Royal Honey VIP/Royal Honey VIP.jpeg"],
            offer: 20,
            unit: "30 Pack 30 Pills Per Box",
            price: 1000,
            MOQ: "100 Box",
          },
          {
            id: 54,
            name: "vROX Silver Single Pack",
            image: ["/Honey/Royal Honey VIP/RoYAL hONEY.jpeg"],
            offer: 20,
            unit: "30 Pack 30 Pills Per Box",
            price: 1000,
            MOQ: "100 Box",
          },
          {
            id: 55,
            name: "7K Single Pack",
            image: ["/Honey/Royal Honey VIP/VIP Honey.jpeg"],
            offer: 20,
            unit: "24 Pack 24 Pills Per Box",
            price: 1000,
            MOQ: "100 Box",
          },
          {
            id: 56,
            name: "Trozan-X Single Pack",
            image: ["/Honey/Secret Miracel Honey/Secret Miracel Honey.jpeg"],
            offer: 20,
            unit: "24 Pack 24 Pills Per Box",
            price: 1000,
            MOQ: "100 Box",
          },
          {
            id: 57,
            name: "Stiff ROX Singlepack",
            image: ["/Honey/Vitamax Double shot/Vitamax Double shot.jpeg"],
            offer: 20,
            unit: "24 Pack 24 Pills Per Box",
            price: 1000,
            MOQ: "100 Box",
          },
          {
            id: 58,
            name: "Strong Back Singlepack",
            image: ["/Honey/Vitamax Double shot/Vitamax Honey.jpeg"],
            offer: 20,
            unit: "24 Pack 24 Pills Per Box",
            price: 1000,
            MOQ: "100 Box",
          },
          {
            id: 59,
            name: "Spnanish Fly Twin Pack",
            image: ["/Pills/100k-Gold/100k-Gold-Front-Side.png"],
            offer: 20,
            unit: "24 Pack 48 Pills Per Box",
            price: 1000,
            MOQ: "100 Box",
          },
          {
            id: 60,
            name: "HAMMER Stroke Single Pack",
            image: ["/Pills/Bullet-3000/Bullet-3000-Front-Side.png"],
            offer: 20,
            unit: "24 Pack 24 Pills Per Box",
            price: 1000,
            MOQ: "100 Box",
          },
          {
            id: 61,
            name: "Jack Hammer Single Pack",
            image: ["/Pills/Magnum-1000k/Magnum-1000k-Front-Side-Double.png"],
            offer: 20,
            unit: "24 Pack 24 Pills Per Box",
            price: 1000,
            MOQ: "100 Box",
          },
          {
            id: 62,
            name: "WET XXX Single Pack",
            image: ["/Pills/Magnum-Gold-1000k/Magnum-Gold-1000k-Gold-Side.png"],
            offer: 20,
            unit: "24 Pack 24 Pills Per Box",
            price: 1000,
            MOQ: "100 Box",
          },
          {
            id: 63,
            name: "SEXSYNERGY Single Pack",
            image: [
              "/Pills/Magnum-Platinum-250k/Magnum-Platinum-250k-Front-Side.png",
            ],
            offer: 20,
            unit: "40 Pack 40 Pills Per Pack",
            price: 1000,
            MOQ: "100 Box",
          },
          {
            id: 64,
            name: "Gold 14K Single Pack",
            image: ["/Pills/100k-Gold/100k-Gold-Front-Side.png"],
            offer: 20,
            unit: "24 Pack 24 Pills Per Box",
            price: 1000,
            MOQ: "100 Box",
          },
          {
            id: 65,
            name: "Wow Panther Single Pack",
            image: ["/Pills/Opal-Black/Opal-Black-Front-Side.png"],
            offer: 20,
            unit: "40 Pack 40 Pills Per Box",
            price: 1000,
            MOQ: "100 Box",
          },
          {
            id: 66,
            name: "Brahma Single Pack",
            image: ["/Pills/Shilajit-1000k/Shilajit-1000k-Front-Side.png"],
            offer: 20,
            unit: "40 Pack 40 Pills Per Box",
            price: 1000,
            MOQ: "100 Box",
          },
        ],
      },
    ],
  },
  {
    title: "Female Enhancement",
    subCategory: [
      {
        title: "Liquid Shots",
        items: [
          {
            id: 67,
            name: "Pink Pussy Cat Liquid Shot ",
            image: ["/Pills/Zesus-250k/Zesus-250k-Front-Side.png"],
            offer: 20,
            unit: "12 Bottles Per Box",
            price: 2500,
            MOQ: "20 Box",
          },
        ],
      },
      {
        title: "Pills",
        items: [
          {
            id: 68,
            name: "Kangaroo Pink Single Pack Large Box",
            image: ["/Pills/100k-Gold/100k-Gold-Front-Side.png"],
            offer: 20,
            unit: "36 Pack Per Box, 48 Box Per Carton",
            price: 2500,
            MOQ: "96 Box",
          },
          {
            id: 69,
            name: "Pink Pussycat Single Pack",
            image: [
              "/Pills/Black-Panther-350k/Black-Panther-350k-Front-Side.png",
            ],
            offer: 20,
            unit: "24 Pack 24 Pills Per Box",
            price: 2500,
            MOQ: "100 Box",
          },
          {
            id: 70,
            name: "Pink Pussycat Twin Pack",
            image: [
              "/Pills/Magnum-Platinum-250k/Magnum-Platinum-250k-Front-Side.png",
            ],
            offer: 20,
            unit: "24 Pack 48 Pills Per Box",
            price: 2500,
            MOQ: "100 Box",
          },
        ],
      },
    ],
  },
  {
    title: "Condoms",
    subCategory: [
      {
        title: "Male Condoms",
        items: [
          {
            id: 71,
            name: "Magnum Trojan Condom 3 in 1 Box",
            image: ["/condom/3pcs latex.jpeg"],
            offer: 20,
            unit: "3 latex Per Box",
            price: 1200,
            MOQ: "1200 Box",
          },
          {
            id: 72,
            name: "Magnum Trojan Condom 40/48 in 1 Box",
            image: ["/condom/48pcs latex.jpeg"],
            offer: 20,
            unit: "40/48 Latex Per Box",
            price: 1000,
            MOQ: "100 Box",
          },
        ],
      },
    ],
  },
  {
    title: "Cannabies Accessories",
    subCategory: [
      {
        title: "Rolling Paper",
        items: [
          {
            id: 73,
            name: "RAW Classic Kingsize Slim Rolling Paper",
            image: ["/Cannabies Accessories/1.png"],
            offer: 20,
            unit: "32 Leaves Per Booklets, 50 Booklets Per Box, 50 Box Per Carton",
            price: 1000,
            MOQ: "100 Box",
          },
          {
            id: 74,
            name: "RAW Black Kingsize Slim Rolling Paper",
            image: ["/Cannabies Accessories/2.png"],
            offer: 20,
            unit: "32 Leaves Per Booklets, 50 Booklets Per Box, 50 Box Per Carton",
            price: 1200,
            MOQ: "100 Box",
          },
          {
            id: 75,
            name: "RAW Kingsize with Tips Rolling Paper",
            image: ["/Cannabies Accessories/3.png"],
            offer: 20,
            unit: "32 Leaves Per Booklets, 24 Booklets Per Box, 40 Box Per Carton",
            price: 1200,
            MOQ: "100 Box",
          },
          {
            id: 76,
            name: "OCB Premium Slim Rolling Paper",
            image: ["/Cannabies Accessories/4.png"],
            offer: 20,
            unit: "32 Leaves Per Booklets, 50 Booklets Per Box, 50 Box Per Carton",
            price: 1000,
            MOQ: "100 Box",
          },
          {
            id: 77,
            name: "OCB Premium Slim with Tips Rolling Paper",
            image: ["/Cannabies Accessories/5.png"],
            offer: 20,
            unit: "32 Leaves Per Booklets, 32 Booklets Per Box, 24 Box Per Carton",
            price: 1200,
            MOQ: "100 Box",
          },
          {
            id: 78,
            name: "OCB Brown Slim Rolling Paper",
            image: ["/Cannabies Accessories/6.png"],
            offer: 20,
            unit: "32 Leaves Per Booklets, 32 Booklets Per Box, 24 Box Per Carton",
            price: 1200,
            MOQ: "100 Box",
          },
          {
            id: 79,
            name: "Big Bambu Classic Rolling Paper",
            image: ["/Cannabies Accessories/1.png"],
            offer: 20,
            unit: "33 Leaves Per Booklets, 50 Booklets Per Box, 50 Box Per Carton",
            price: 2000,
            MOQ: "100 Box",
          },
          {
            id: 80,
            name: "Big Bambu Pure Hemp Paper",
            image: ["/Cannabies Accessories/2.png"],
            offer: 20,
            unit: "33 Leaves Per Booklets, 50 Booklets Per Box, 50 Box Per Carton",
            price: 2000,
            MOQ: "100 Box",
          },
          {
            id: 81,
            name: "Elements Kingsize Slim Papers",
            image: ["/Cannabies Accessories/3.png"],
            offer: 20,
            unit: "33 Leaves Per Booklets, 50 Booklets Per Box",
            price: 1000,
            MOQ: "100 Box",
          },
          {
            id: 82,
            name: "RAW Cone 1 1/4 Classic 6PK",
            image: ["/Cannabies Accessories/4.png"],
            offer: 20,
            unit: "32 Cones Per Pack, 6 Pack Per Box, 24 Box Per Carton",
            price: 1000,
            MOQ: "100 Box",
          },
          {
            id: 83,
            name: "RAW Cone 1 1/4 Classic 6PK",
            image: ["/Cannabies Accessories/5.png"],
            offer: 20,
            unit: "32 Cones Per Pack, 3 Pack Per Box, 24 Box Per Carton",
            price: 1000,
            MOQ: "100 Box",
          },
          {
            id: 84,
            name: "RAW 32 11/4 Classic Cones",
            image: ["/Cannabies Accessories/6.png"],
            offer: 20,
            unit: "32 Cones Per Pack, 3 Pack Per Box, 24 Box Per Carton",
            price: 1000,
            MOQ: "100 Box",
          },
        ],
      },
    ],
  },
];
export const getProductByBrandName = (menuItems, title) => {
  const productTitle = title.productTitle;
  for (let subCategory of menuItems) {
    if (productTitle) {
      const foundProduct = subCategory.subCategory.find(
        (product) => product.title.toLowerCase() === productTitle.toLowerCase()
      );
      if (foundProduct) {
        return foundProduct;
      }
    }
  }

  return null;
};
