export const Cannabies = [
    {
        title: "Rolling Paper",
        products:[
            {
                id: 73,
                name: "RAW Classic Kingsize Slim Rolling Paper",
                image: ["/Cannabies Accessories/1.png"],
                percentage: "20%",
                unit: "32 Leaves Per Booklets, 50 Booklets Per Box, 50 Box Per Carton",
                price: 1000,
                MOQ: "100 Box",
              },
              {
                id: 74,
                name: "RAW Black Kingsize Slim Rolling Paper",
                image: ["/Cannabies Accessories/2.png"],
                percentage: "20%",
                unit: "32 Leaves Per Booklets, 50 Booklets Per Box, 50 Box Per Carton",
                price: 1200,
                MOQ: "100 Box",
              },
              {
                id: 75,
                name: "RAW Kingsize with Tips Rolling Paper",
                image: ["/Cannabies Accessories/3.png"],
                percentage: "20%",
                unit: "32 Leaves Per Booklets, 24 Booklets Per Box, 40 Box Per Carton",
                price: 1200,
                MOQ: "100 Box",
              },
              {
                id: 76,
                name: "OCB Premium Slim Rolling Paper",
                image: ["/Cannabies Accessories/4.png"],
                percentage: "20%",
                unit: "32 Leaves Per Booklets, 50 Booklets Per Box, 50 Box Per Carton",
                price: 1000,
                MOQ: "100 Box",
              },
              {
                id: 77,
                name: "OCB Premium Slim with Tips Rolling Paper",
                image: ["/Cannabies Accessories/5.png"],
                percentage: "20%",
                unit: "32 Leaves Per Booklets, 32 Booklets Per Box, 24 Box Per Carton",
                price: 1200,
                MOQ: "100 Box",
              },
              {
                id: 78,
                name: "OCB Brown Slim Rolling Paper",
                image: ["/Cannabies Accessories/6.png"],
                percentage: "20%",
                unit: "32 Leaves Per Booklets, 32 Booklets Per Box, 24 Box Per Carton",
                price: 1200,
                MOQ: "100 Box",
              },
              {
                id: 79,
                name: "Big Bambu Classic Rolling Paper",
                image: ["/Cannabies Accessories/1.png"],
                percentage: "20%",
                unit: "33 Leaves Per Booklets, 50 Booklets Per Box, 50 Box Per Carton",
                price: 2000,
                MOQ: "100 Box",
              },
              {
                id: 80,
                name: "Big Bambu Pure Hemp Paper",
                image: ["/Cannabies Accessories/2.png"],
                percentage: "20%",
                unit: "33 Leaves Per Booklets, 50 Booklets Per Box, 50 Box Per Carton",
                price: 2000,
                MOQ: "100 Box",
              },
              {
                id: 81,
                name: "Elements Kingsize Slim Papers",
                image: ["/Cannabies Accessories/3.png"],
                percentage: "20%",
                unit: "33 Leaves Per Booklets, 50 Booklets Per Box",
                price: 1000,
                MOQ: "100 Box",
              },
              {
                id: 82,
                name: "RAW Cone 1 1/4 Classic 6PK",
                image: ["/Cannabies Accessories/4.png"],
                percentage: "20%",
                unit: "32 Cones Per Pack, 6 Pack Per Box, 24 Box Per Carton",
                price: 1000,
                MOQ: "100 Box",
              },
              {
                id: 83,
                name: "RAW Cone 1 1/4 Classic 6PK",
                image: ["/Cannabies Accessories/5.png"],
                percentage: "20%",
                unit: "32 Cones Per Pack, 3 Pack Per Box, 24 Box Per Carton",
                price: 1000,
                MOQ: "100 Box",
              },
              {
                id: 84,
                name: "RAW 32 11/4 Classic Cones",
                image: ["/Cannabies Accessories/6.png"],
                percentage: "20%",
                unit: "32 Cones Per Pack, 3 Pack Per Box, 24 Box Per Carton",
                price: 1000,
                MOQ: "100 Box",
              },           
        ]

    }
]