export const allProducts = [
  {
    id: 1,
    name: "Royal Honey For Men – Gold (12 Sachets – 20 G)",
    image: ["/Honey/Royal Honey VIP/Royal Honey VIP.jpeg"],
    price: 19.99,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    unit: "12 Sachet Per Box",
    reviews: "5 reviews",
    category: "Honey",
    createdBy: "Munna",
    updatedAt: "13/04/2023",
  },
  {
    id: 2,
    name: "Royal Honey VIP 22g Pouches",
    image: ["/Honey/Royal Honey VIP/RoYAL hONEY.jpeg"],
    price: 49.99,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    unit: "15 Pouches Per Box",
    reviews: "4.5 reviews",
    category: "Honey",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 3,
    name: "Etumax Honey 20g Sachet",
    image: ["/Honey/Etumax Honey/Etumax(4).jpeg"],
    price: 19.99,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    unit: "12 Sachet Per Box",
    reviews: "4.5 reviews",
    category: "Honey",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 4,
    name: "Etumax Honey 22g Pouches",
    image: ["/Honey/Etumax Honey/Etumax.jpeg"],
    price: 49.99,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    unit: "15 Pouches Per Box",
    reviews: "4.5 reviews",
    category: "Honey",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 5,
    name: "Black Bull Honey 22g Pouches",
    image: ["/Honey/Black Bull Honey/Black Bull Honey.jpg"],

    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    unit: "12 Poches Per Box",
    price: 30.99,
    reviews: "4.5 reviews",
    category: "Honey",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 6,
    name: "Black Bull Honey 20g Pouches",
    image: ["/Honey/Black Bull Honey/Black Bull.jpeg"],
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    unit: "15 Pouches Per Box",
    price: 29.99,
    reviews: "4.5 reviews",
    category: "Honey",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 7,
    name: "Red Bull Honey 22g Pouches",
    image: ["/Honey/Red Bull Honey/Red Bull Honey.jpeg"],
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    unit: "12 Poches Per Box",
    price: 39.99,
    reviews: "4.5 reviews",
    category: "Honey",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 8,
    name: "Red Bull Honey 20g Pouches",
    image: ["/Honey/Red Bull Honey/Red Bull Honey.jpeg"],
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    unit: "15 Pouches Per Box",
    price: 19.99,
    reviews: "4.5 reviews",
    category: "Honey",
    createdBy: "Munna",
    updatedAt: "13/04/2023",
  },
  {
    id: 9,
    name: "Blue Bull Honey 22g Pouches",
    image: ["/Honey/Blue Bull Honey/Blue Bull.jpeg"],
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    unit: "12 Poches Per Box",
    price: 48.99,
    reviews: "4.5 reviews",
    category: "Honey",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 10,
    name: "Blue Bull Honey 20g Pouches",
    image: ["/Honey/Blue Bull Honey/Blue Bull.jpeg"],
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    unit: "15 Pouches Per Box",
    price: 19.99,
    MOQ: "280 Box",
    reviews: "4.5 reviews",
    category: "Honey",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 11,
    name: "Leopard Miracle Honey 15g Sachet",
    image: ["/Honey/Leopard Miracle Honey VIP/Leopard Miracle VIP.jpeg"],
    unit: "12 Sachet Per Box",
    price: 11.99,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Honey",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 12,
    name: "Leopard Miracle Honey 22g Pouches",
    image: ["/Honey/Leopard Miracle Honey VIP/Leopard Miracle VIP.jpeg"],
    unit: "15 Pouches Per Box",
    price: 14.99,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Honey",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 13,
    name: "Secret Miracle Honey 15g Sachet",
    image: ["/Honey/Secret Miracel Honey/Secret Miracel Honey.jpeg"],
    unit: "12 Pouches Per Box",
    price: 25.99,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Honey",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 14,
    name: "Vitamax Double Shot 20g Sachet",
    image: ["/Honey/Vitamax Double shot/Vitamax Double shot.jpeg"],
    unit: "10 Pouches Per Box",
    price: 29.99,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Honey",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 15,
    name: "Rhino 69 Liquid Shot ",
    image: [
      "/Pills/Rhino-69-1000k/Rhino-69-1000k-Front-Side.png",
      "/Pills/Rhino-69-1000k/Rhino-69-1000k-Rear-Side.png",
    ],
    unit: "12 Bottles Per Box",
    price: 59.99,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Liquid Shot",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 16,
    name: "Rhino Platinum Liquid Shot",
    image: [
      "/Pills/Rhino-69-1200k/Rhino-69-1200k-Front-Side.png",
      "/Pills/Rhino-69-1200k/Rhino-69-1200k-Rear-Side.png",
    ],
    unit: "12 Bottles Per Box",
    price: 59.99,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Liquid Shot",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 17,
    name: "Hard Steel Liquid Shot",
    image: [
      "/Pills/Opal-Black/Opal-Black-Front-Side.png",
      "/Pills/Opal-Black/Opal-Black-Rear-Side.png",
    ],
    unit: "12 Bottles Per Box",
    price: 69.99,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Liquid Shot",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 18,
    name: "Super Man Liquid Shot",
    image: [
      "/Pills/Bullet-3000/Bullet-3000-Front-Side.png",
      "/Pills/Bullet-3000/Bullet-3000-Rear-Side.png",
    ],
    unit: "12 Bottles Per Box",
    price: 69.99,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Liquid Shot",
    createdBy: "Munna",
    updatedAt: "13/04/2023",
  },
  {
    id: 19,
    name: "Rhino 100k Gold",
    image: [
      "/Pills//100k-Gold/100k-Gold-Front-Side.png",
      "/Pills/100k-Gold/100k-Gold-Rear-Side.png",
    ],
    unit: "12 Pcs Per Box",
    price: 60,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 20,
    name: "Rhino Black-Panther-350k",
    image: [
      "/Pills/Black-Panther-350k/Black-Panther-350k-Front-Side.png",
      "/Pills/Black-Panther-350k/Black-Panther-350k-Rear-Side.png",
    ],
    unit: "24 Pcs Per Box",
    price: 50,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 21,
    name: "Bullet-3000",
    image: [
      "/Pills/Bullet-3000/Bullet-3000-Front-Side.png",
      "/Pills/Bullet-3000/Bullet-3000-Rear-Side.png",
    ],
    unit: "30 Pcs Per Bottle",
    price: 80,
    MOQ: "100 Bottles",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 22,
    name: "Magnum-1000k",
    image: [
      "/Pills/Magnum-1000k/Magnum-1000k-Front-Side-Double.png",
      "/Pills/Magnum-1000k/Magnum-1000k-Front-Side-Double.png",
    ],
    unit: "2 Pcs Per Box",
    price: 25,
    MOQ: "100 Box",
    percentage: "20%",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 23,
    name: "Magnum-Platinum-250k",
    image: [
      "/Pills/Magnum-Platinum-250k/Magnum-Platinum-250k-Front-Side.png",
      "/Pills/Magnum-Platinum-250k/Magnum-Platinum-250k-Rear-Side.png",
    ],
    unit: "30 Pcs Per Bottle",
    price: 80,
    MOQ: "100 Bottles",
    percentage: "20%",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 24,
    name: "Magnum-Gold-1000k",
    image: [
      "/Pills/Magnum-Gold-1000k/Magnum-Gold-1000k-Gold-Side.png",
      "/Pills/Magnum-Gold-1000k/Magnum-Gold-1000k-Rear-Side.png",
    ],
    unit: "30 Pcs Per Bottle",
    price: 80,
    MOQ: "100 Bottles",
    percentage: "20%",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 25,
    name: "Spanish-fly-22000-Green",
    image: [
      "/Pills/Spanish-fly-22000-Green/Spanish-fly-22000-Front-Side-Green.png",
      "/Pills/Spanish-fly-22000-Green/Spanish-fly-22000-Rear-Side-Green.png",
    ],
    unit: "1 Pcs Per Bag",
    price: 15,
    MOQ: "500 Bag",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 26,
    name: "Spanish-fly-22000-Red",
    image: [
      "/Pills/Spanish-fly-22000-Red/Spanish-fly-22000-Front-Side-Red.png",
      "/Pills/Spanish-fly-22000-Red/Spanish-fly-22000-Rear-Side Red.png",
    ],
    unit: "25 Pcs Per Pack",
    price: 90,
    MOQ: "100 Pack",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 27,
    name: "Bullet-3000",
    image: [
      "/Pills/Bullet-3000/Bullet-3000-Front-Side.png",
      "/Pills/Bullet-3000/Bullet-3000-Rear-Side.png",
    ],
    unit: "30 Pack Per Box, 57 Box Per Carton",
    price: 50,
    MOQ: "114 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 28,
    name: "Opal-Black",
    image: [
      "/Pills/Opal-Black/Opal-Black-Front-Side.png",
      "/Pills/Opal-Black/Opal-Black-Rear-Side.png",
    ],
    unit: "30 Pack Per Box, 57 Box Per Carton",
    price: 50,
    MOQ: "114 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "13/04/2023",
  },
  {
    id: 29,
    name: "Zesus-250k",
    image: [
      "/Pills/Zesus-250k/Zesus-250k-Front-Side.png",
      "/Pills/Zesus-250k/Zesus-250k-Rear-Side.png",
    ],
    unit: "36 Pack Per Box, 48 Box Per Carton",
    price: 50,
    MOQ: "96 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 30,
    name: "Rhino-69-1000k",
    image: [
      "/Pills/Rhino-69-1000k/Rhino-69-1000k-Front-Side.png",
      "/Pills/Rhino-69-1000k/Rhino-69-1000k-Rear-Side.png",
    ],
    unit: "24 Pack 48 Pills Per Box",
    price: 100,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Liquid Shot",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 31,
    name: "Rhino-69-1200k",
    image: [
      "/Pills/Rhino-69-1200k/Rhino-69-1200k-Front-Side.png",
      "/Pills/Rhino-69-1200k/Rhino-69-1200k-Rear-Side.png",
    ],
    unit: "24 Pack 48 Pills Per Box",
    price: 100,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Liquid Shot",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 32,
    name: "Rhino-69-1300k",
    image: [
      "/Pills/Rhino-69-1300k/Rhino-69-1300k-Front-Side.png",
      "/Pills/Rhino-69-1300k/Rhino-69-1300k-Rear-Side.png",
    ],
    unit: "24 Pack 48 Pills Per Box",
    price: 100,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Liquid Shot",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 33,
    name: "Rhino-69-1300k-Double",
    image: [
      "/Pills/Rhino-69-1300k-Double/Rhino-69-1300k-Front-Side-Double.png",
      "/Pills/Rhino-69-1300k-Double/Rhino-69-1300k-Rear-Side-Double.png",
    ],
    unit: "24 Pack 24 Pills Per Box",
    price: 100,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Liquid Shot",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 34,
    name: "Rhino-69-1400k",
    image: [
      "/Pills/Rhino-69-1400k/Rhino-69-1400k-Front-Side.png",
      "/Pills/Rhino-69-1400k/Rhino-69-1400k-Rear-Side.png",
    ],
    unit: "24 Pack 72 Pills Per Box",
    price: 180,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Liquid Shot",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 35,
    name: "Rhino-69-1500k-Double",
    image: [
      "/Pills/Rhino-69-1500k-Double/Rhino-69-1500k-Front-Side-Double.png",
      "/Pills/Rhino-69-1500k-Double/Rhino-69-1500k-Rear-Side-Double.png",
    ],
    unit: "24 Pack 24 Pills Per Box, 12 Large Card+12 Small Card",
    price: 180,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Liquid Shot",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 36,
    name: "Rhino-69-1600k",
    image: [
      "/Pills/Rhino-69-1600k/Rhino-69-1600k-Front-Side.png",
      "/Pills/Rhino-69-1600k/Rhino-69-1600k-Rear-Side.png",
    ],
    unit: "24 Pack 24 Pills Per Box",
    price: 80,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Liquid Shot",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 37,
    name: "Rhino-69-1600k-Double",
    image: [
      "/Pills/Rhino-69-1600k-Double/Rhino-69-1600k-Front-Side-Double.png",
      "/Pills/Rhino-69-1600k-Double/Rhino-69-1600k-Rear-Side-Double.png",
    ],
    unit: "24 Pack 24 Pills Per Box",
    price: 80,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Liquid Shot",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 38,
    name: "Rhino-69-1700k-double",
    image: [
      "/Pills/Rhino-69-1700k-double/Rhino-69-1700k-Front-Side-double.png",
      "/Pills/Rhino-69-1700k-double/Rhino-69-1700k-Rear-Side-double.png",
    ],
    unit: "24 Pack 24 Pills Per Box",
    price: 80,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Liquid Shot",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 39,
    name: "Rhino-69-1700k-Single",
    image: [
      "/Pills/Rhino-69-1700k-Single/Rhino-69-1700k-Front-Side-Single.png",
      "/Pills/Rhino-69-1700k-Single/Rhino-69-1700k-Rear-Side-Single.png",
    ],
    unit: "24 Pack 24 Pills Per Box",
    price: 90,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Liquid Shot",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 40,
    name: "Rhino-69-1800k-Double",
    image: [
      "/Pills/Rhino-69-1800k-Double/Rhino-69-1800k-Front-Side-Double.png",
      "/Pills/Rhino-69-1800k-Double/Rhino-69-1800k-Rear-Side-Double.png",
    ],
    unit: "24 Pack 24 Pills Per Box",
    price: 90,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Liquid Shot",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 41,
    name: "Rhino-69-1900k",
    image: [
      "/Pills/Rhino-69-1900k/Rhino-69-1900k-Front-Side.png",
      "/Pills/Rhino-69-1900k/Rhino-69-1900k-Rear-Side.png",
    ],
    unit: "24 Pack 120 Pills Per Box",
    price: 120,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Liquid Shot",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 42,
    name: "Rhino-69-1900k-Single",
    image: [
      "/Pills/Rhino-69-1900k-Single/Rhino-69-1900k-Front-Side-Single.png",
      "/Pills/Rhino-69-1900k-Single/Rhino-69-1900k-Rear-Side-Single.png",
    ],
    unit: "24 Pack 120 Pills Per Box",
    price: 120,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Liquid Shot",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 43,
    name: "Rhino-69-2100k",
    image: [
      "/Pills/Rhino-69-2100k/Rhino-69-2100k-Front-Side.png",
      "/Pills/Rhino-69-2100k/Rhino-69-2100k-Rear-Side.png",
    ],
    unit: "24 Pack 120 Pills Per Box",
    price: 120,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Liquid Shot",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 44,
    name: "Rhino-69-2100k-Single",
    image: [
      "/Pills/Rhino-69-2100k-Single/Rhino-69-2100k-Front-Side-Single.png",
      "/Pills/Rhino-69-2100k-Single/Rhino-69-2100k-Rear-Side-Single.png",
    ],
    unit: "24 Pack 120 Pills Per Box",
    price: 100,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Liquid Shot",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 45,
    name: "Rhino-69-2400k-Red",
    image: [
      "/Pills/Rhino-69-2400k-Red/Rhino-69-2400k-Front-Side-Red.png",
      "/Pills/Rhino-69-2400k-Red/Rhino-69-2400k-Rear-Side-Red.png",
    ],
    unit: "24 Pack 120 Pills Per Box",
    price: 100,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Liquid Shot",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 46,
    name: "Rhino-69-2400k-Red-Single",
    image: [
      "/Pills/Rhino-69-2400k-Red-Single/Rhino-69-2400k-Front-Side-Red-Single.png",
      "/Pills/Rhino-69-2400k-Red-Single/Rhino-69-2400k-Rear-Side-Red-Single.png",
    ],
    unit: "24 Pack 120 Pills Per Box",
    price: 100,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Liquid Shot",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 47,
    name: "Rhino-69-18000-Single",
    image: [
      "/Pills/Rhino-69-18000-Single/Rhino-69-18000-Front-Side-Single.png",
      "/Pills/Rhino-69-18000-Single/Rhino-69-18000-Rear-Side-Single.png",
    ],
    unit: "24 Pack 120 Pills Per Box",
    price: 120,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Liquid Shot",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 48,
    name: "Premier ZEN Gold 13000 Single Pack",
    image: [
      "/Honey/Black Bull Honey/Black Bull Honey.jpg",
      "/Honey/Black Bull Honey/Black Bull.jpeg",
    ],
    unit: "24 Pack 24 Pills Per Box",
    price: 80,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 49,
    name: "Premier ZEN 7000 Single Pack",
    image: ["/Honey/Blue Bull Honey/Blue Bull.jpeg"],
    unit: "24 Pack 24 Pills Per Box, 12 Large Card+12 Small Card",
    price: 90,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 50,
    name: "Premier ZEN Black 5000 Single Pack",
    image: ["/Honey/Leopard Honey/Leopard MiracleHoney.jpg"],
    unit: "24 Pack 24 Pills Per Box, 12 Large Card+12 Small Card",
    price: 100,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 51,
    name: "SWAG 50 Red Single Pack",
    image: ["/Honey/Leopard Miracle Honey VIP/Leopard Miracle VIP.jpeg"],
    unit: "24 Pack 24 Pills Per Box",
    price: 100,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 52,
    name: "SWAG 100K Yellow Single Pack",
    image: ["/Honey/Red Bull Honey/Red Bull Honey.jpeg"],
    unit: "24 Pack 24 Pills Per Box",
    price: 90,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 53,
    name: "vROX Gold Single Pack",
    image: ["/Honey/Royal Honey VIP/Royal Honey VIP.jpeg"],
    unit: "30 Pack 30 Pills Per Box",
    price: 120,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 54,
    name: "vROX Silver Single Pack",
    image: ["/Honey/Royal Honey VIP/RoYAL hONEY.jpeg"],
    unit: "30 Pack 30 Pills Per Box",
    price: 100,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 55,
    name: "7K Single Pack",
    image: ["/Honey/Royal Honey VIP/VIP Honey.jpeg"],
    unit: "24 Pack 24 Pills Per Box",
    price: 90,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 56,
    name: "Trozan-X Single Pack",
    image: ["/Honey/Secret Miracel Honey/Secret Miracel Honey.jpeg"],
    unit: "24 Pack 24 Pills Per Box",
    price: 80,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 57,
    name: "Stiff ROX Singlepack",
    image: ["/Honey/Vitamax Double shot/Vitamax Double shot.jpeg"],
    unit: "24 Pack 24 Pills Per Box",
    price: 80,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 58,
    name: "Strong Back Singlepack",
    image: ["/Honey/Vitamax Double shot/Vitamax Honey.jpeg"],
    unit: "24 Pack 24 Pills Per Box",
    price: 100,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 59,
    name: "Spnanish Fly Twin Pack",
    image: ["/Pills/100k-Gold/100k-Gold-Front-Side.png"],
    unit: "24 Pack 48 Pills Per Box",
    price: 80,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 60,
    name: "HAMMER Stroke Single Pack",
    image: ["/Pills/Bullet-3000/Bullet-3000-Front-Side.png"],
    unit: "24 Pack 24 Pills Per Box",
    price: 100,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "1/04/2023",
  },
  {
    id: 61,
    name: "Jack Hammer Single Pack",
    image: ["/Pills/Magnum-1000k/Magnum-1000k-Front-Side-Double.png"],
    unit: "24 Pack 24 Pills Per Box",
    price: 80,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 62,
    name: "WET XXX Single Pack",
    image: ["/Pills/Magnum-Gold-1000k/Magnum-Gold-1000k-Gold-Side.png"],
    unit: "24 Pack 24 Pills Per Box",
    price: 100,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 63,
    name: "SEXSYNERGY Single Pack",
    image: ["/Pills/Magnum-Platinum-250k/Magnum-Platinum-250k-Front-Side.png"],
    unit: "40 Pack 40 Pills Per Pack",
    price: 100,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 64,
    name: "Gold 14K Single Pack",
    image: ["/Pills/100k-Gold/100k-Gold-Front-Side.png"],
    unit: "24 Pack 24 Pills Per Box",
    price: 100,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 65,
    name: "Wow Panther Single Pack",
    image: ["/Pills/Opal-Black/Opal-Black-Front-Side.png"],
    unit: "40 Pack 40 Pills Per Box",
    price: 80,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 66,
    name: "Brahma Single Pack",
    image: ["/Pills/Shilajit-1000k/Shilajit-1000k-Front-Side.png"],
    unit: "40 Pack 40 Pills Per Box",
    price: 120,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 67,
    name: "Pink Pussy Cat Liquid Shot ",
    image: ["/Pills/Zesus-250k/Zesus-250k-Front-Side.png"],
    unit: "12 Bottles Per Box",
    price: 250,
    MOQ: "20 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Liquid Shot",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 68,
    name: "Kangaroo Pink Single Pack Large Box",
    image: ["/Pills/100k-Gold/100k-Gold-Front-Side.png"],
    unit: "36 Pack Per Box, 48 Box Per Carton",
    price: 250,
    MOQ: "96 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 69,
    name: "Pink Pussycat Single Pack",
    image: ["/Pills/Black-Panther-350k/Black-Panther-350k-Front-Side.png"],
    unit: "24 Pack 24 Pills Per Box",
    price: 250,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 70,
    name: "Pink Pussycat Twin Pack",
    image: ["/Pills/Magnum-Platinum-250k/Magnum-Platinum-250k-Front-Side.png"],
    unit: "24 Pack 48 Pills Per Box",
    price: 250,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Pills",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 71,
    name: "Magnum Trojan Condom 3 in 1 Box",
    image: ["/condom/3pcs latex.jpeg"],
    unit: "3 latex Per Box",
    price: 120,
    MOQ: "1200 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Condom",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 72,
    name: "Magnum Trojan Condom 40/48 in 1 Box",
    image: ["/condom/48pcs latex.jpeg"],
    unit: "40/48 Latex Per Box",
    price: 100,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Condom",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 73,
    name: "RAW Classic Kingsize Slim Rolling Paper",
    image: ["/Cannabies Accessories/1.png"],
    unit: "32 Leaves Per Booklets, 50 Booklets Per Box, 50 Box Per Carton",
    price: 100,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Rolling Paper",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 74,
    name: "RAW Black Kingsize Slim Rolling Paper",
    image: ["/Cannabies Accessories/2.png"],
    unit: "32 Leaves Per Booklets, 50 Booklets Per Box, 50 Box Per Carton",
    price: 120,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Rolling Paper",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 75,
    name: "RAW Kingsize with Tips Rolling Paper",
    image: ["/Cannabies Accessories/3.png"],
    unit: "32 Leaves Per Booklets, 24 Booklets Per Box, 40 Box Per Carton",
    price: 100,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Rolling Paper",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 76,
    name: "OCB Premium Slim Rolling Paper",
    image: ["/Cannabies Accessories/4.png"],
    unit: "32 Leaves Per Booklets, 50 Booklets Per Box, 50 Box Per Carton",
    price: 80,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Rolling Paper",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 77,
    name: "OCB Premium Slim with Tips Rolling Paper",
    image: ["/Cannabies Accessories/5.png"],
    unit: "32 Leaves Per Booklets, 32 Booklets Per Box, 24 Box Per Carton",
    price: 100,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Rolling Paper",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 78,
    name: "OCB Brown Slim Rolling Paper",
    image: ["/Cannabies Accessories/6.png"],
    unit: "32 Leaves Per Booklets, 32 Booklets Per Box, 24 Box Per Carton",
    price: 120,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Rolling Paper",
    createdBy: "Munna",
    updatedAt: "13/04/2023",
  },
  {
    id: 79,
    name: "Big Bambu Classic Rolling Paper",
    image: ["/Cannabies Accessories/1.png"],
    unit: "33 Leaves Per Booklets, 50 Booklets Per Box, 50 Box Per Carton",
    price: 200,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Rolling Paper",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 80,
    name: "Big Bambu Pure Hemp Paper",
    image: ["/Cannabies Accessories/2.png"],
    unit: "33 Leaves Per Booklets, 50 Booklets Per Box, 50 Box Per Carton",
    price: 200,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Rolling Paper",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 81,
    name: "Elements Kingsize Slim Papers",
    image: ["/Cannabies Accessories/3.png"],
    unit: "33 Leaves Per Booklets, 50 Booklets Per Box",
    price: 100,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Rolling Paper",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 82,
    name: "RAW Cone 1 1/4 Classic 6PK",
    image: ["/Cannabies Accessories/4.png"],
    unit: "32 Cones Per Pack, 6 Pack Per Box, 24 Box Per Carton",
    price: 100,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Cone Paper",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 83,
    name: "RAW Cone 1 1/4 Classic 6PK",
    image: ["/Cannabies Accessories/5.png"],
    unit: "32 Cones Per Pack, 3 Pack Per Box, 24 Box Per Carton",
    price: 100,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Cone Paper",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 84,
    name: "RAW 32 11/4 Classic Cones",
    image: ["/Cannabies Accessories/6.png"],
    unit: "32 Cones Per Pack, 3 Pack Per Box, 24 Box Per Carton",
    price: 100,
    MOQ: "100 Box",
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Cone Paper",
    createdBy: "Munna",
    updatedAt: "03/04/2023",
  },
  {
    id: 85,
    image: ["/images/Product/pro-1.png"],
    name: "Rhino 69 600K",
    category: "Male enhancement Supplement",
    quote: "Don't Quit ... ",
    offer: 20,
    price: 100,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Cone Paper",
    createdBy: "Munna",
    updatedAt: "2/03/2023",
  },
  {
    id: 86,
    image: ["/images/Product/pro-2.png"],
    name: "Rhino 69 1900K",
    category: "Male enhancement Supplement",
    quote: "Extra strength",
    price: 150,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Cone Paper",
    createdBy: "Munna",
    updatedAt: "2/03/2023",
  },
  {
    id: 87,
    image: ["/images/Product/pro-3.png"],
    name: "Rhino 69 2400K",
    category: "VIP Royal Honey",
    quote: "Honey for Extra Energy",
    price: 70,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Cone Paper",
    createdBy: "Munna",
    updatedAt: "2/03/2023",
  },
  {
    id: 88,
    image: ["/images/Product/pro-4.png"],
    name: "Rhino 69 10000K",
    category: "Dietary Supplement",
    quote: "Discover the potential",
    price: 80,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Cone Paper",
    createdBy: "Munna",
    updatedAt: "2/03/2023",
  },
  {
    id: 89,
    image: ["/images/Product/pro-5.png"],
    name: "Pink Pussy Cat Liquid Shot ",
    category: "Dietary Supplement",
    quote: "Discover the potential",
    price: 90,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Cone Paper",
    createdBy: "Munna",
    updatedAt: "10/04/2023",
  },
  {
    id: 90,
    image: ["/images/Product/pro-6.png"],
    name: "Rhino 69 4750k",
    category: "Dietary Supplement",
    quote: "Discover the potential",
    price: 50,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Cone Paper",
    createdBy: "Munna",
    updatedAt: "10/04/2023",
  },
  {
    id: 91,
    image: ["/images/Product/pro-7.png"],
    name: "Rhino 69 15000K",
    category: "Dietary Supplement",
    quote: "Discover the potential",
    price: 20,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Cone Paper",
    createdBy: "Munna",
    updatedAt: "10/04/2023",
  },
  {
    id: 92,
    image: ["/images/Product/pro-8.png"],
    name: "Rhino 69 3750K",
    category: "Dietary Supplement",
    quote: "Discover the potential",
    price: 70,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Cone Paper",
    createdBy: "Munna",
    updatedAt: "10/04/2023",
  },
  {
    id: 93,
    image: ["/images/Product/pro-9.png"],
    name: "Rhino 69 23000K",
    category: "Dietary Supplement",
    quote: "Discover the potential",
    price: 22,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Cone Paper",
    createdBy: "Munna",
    updatedAt: "10/04/2023",
  },
  {
    id: 94,
    image: ["/images/Product/pro-10.png"],
    name: "Rhino 69 7500K",
    category: "Dietary Supplement",
    quote: "Discover the potential",
    price: 24,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Cone Paper",
    createdBy: "Munna",
    updatedAt: "10/04/2023",
  },
  {
    id: 95,
    image: ["/images/Product/pro-12.png"],
    name: "Royal Honey VIP 20g Sachet",
    category: "Dietary Supplement",
    quote: "Discover the potential",
    price: 32,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Cone Paper",
    createdBy: "Munna",
    updatedAt: "13/04/2023",
  },
  {
    id: 96,
    image: ["/images/Product/pro-13.png"],
    name: "Royal Honey VIP 20g Sachet",
    category: "Dietary Supplement",
    quote: "Discover the potential",
    price: 43,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Cone Paper",
    createdBy: "Munna",
    updatedAt: "01/04/2023",
  },
  {
    id: 97,
    image: ["/images/Product/pro-14.png"],
    name: "Trojan MAGNUM",
    category: "Dietary Supplement",
    quote: "Discover the potential",
    price: 67,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Cone Paper",
    createdBy: "Munna",
    updatedAt: "01/04/2023",
  },
  {
    id: 98,
    image: ["/images/Product/pro-15.png"],
    name: "BLACK BULL EXTREME",
    category: "Dietary Supplement",
    quote: "Discover the potential",
    price: 23,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Cone Paper",
    createdBy: "Munna",
    updatedAt: "01/04/2023",
  },
  {
    id: 99,
    image: ["/images/Product/pro-16.png"],
    name: "Royal Honey VIP 20g Sachet",
    category: "Dietary Supplement",
    quote: "Discover the potential",
    price: 11,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Cone Paper",
    createdBy: "Munna",
    updatedAt: "01/04/2023",
  },
  {
    id: 100,
    image: ["/images/Product/pro-17.png"],
    name: "Miracle of Honey 20g Sachet",
    category: "Dietary Supplement",
    quote: "Discover the potential",
    price: 7,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Cone Paper",
    createdBy: "Munna",
    updatedAt: "01/04/2023",
  },
  {
    id: 101,
    image: ["/images/Product/pro-18.png"],
    name: "Leopard Miracle Honey 20g Sachet",
    category: "Dietary Supplement",
    quote: "Discover the potential",
    price: 90,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Cone Paper",
    createdBy: "Munna",
    updatedAt: "01/04/2023",
  },
  {
    id: 102,
    image: ["/images/Product/pro-19.png"],
    name: "Red Bull",
    category: "Dietary Supplement",
    quote: "Discover the potential",
    price: 88,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Cone Paper",
    createdBy: "Munna",
    updatedAt: "13/04/2023",
  },
  {
    id: 103,
    image: ["/images/Product/pro-20.png"],
    name: "VITA MAX Double Shot 20g Sachet",
    category: "Dietary Supplement",
    quote: "Discover the potential",
    price: 77,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Cone Paper",
    createdBy: "Munna",
    updatedAt: "1/04/2023",
  },
  {
    id: 104,
    image: ["/images/Product/pro-21.png"],
    name: "ETUMA Royal Honey 20g Sachet",
    category: "Dietary Supplement",
    quote: "Discover the potential",
    price: 99,
    offer: 20,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Cone Paper",
    createdBy: "Munna",
    updatedAt: "1/04/2023",
  },
  {
    id: 105,
    image: ["/images/Product/pro-1.png"],
    name: "Rhino 69 600K",
    category: "Male enhancement Supplement",
    quote: "Don't Quit ... ",
    price: 100,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Cone Paper",
    createdBy: "Munna",
    updatedAt: "1/04/2023",
  },
  {
    id: 106,
    image: ["/images/Product/pro-2.png"],
    name: "Rhino 69 1900K",
    category: "Male enhancement Supplement",
    quote: "Extra strength",
    price: 150,
    offer: 10,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Cone Paper",
    createdBy: "Munna",
    updatedAt: "15/04/2023",
  },
  {
    id: 107,
    image: ["/images/Product/pro-3.png"],
    name: "Rhino 69 2400K",
    category: "VIP Royal Honey",
    quote: "Honey for Extra Energy",
    price: 100,
    offer: 5,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Cone Paper",
    createdBy: "Munna",
    updatedAt: "1/04/2023",
  },
  {
    id: 108,
    image: ["/images/Product/pro-4.png"],
    name: "Rhino 69 10000K",
    category: "Dietary Supplement",
    quote: "Discover the potential",
    price: 120,
    offer: 15,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Cone Paper",
    createdBy: "Munna",
    updatedAt: "13/04/2023",
  },
  {
    id: 109,
    image: ["/images/Product/pro-4.png"],
    name: "Rhino 69 10000K",
    category: "Dietary Supplement",
    quote: "Discover the potential",
    price: 120,
    offer: 10,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Cone Paper",
    createdBy: "Munna",
    updatedAt: "01/04/2023",
  },
  {
    id: 110,
    image: ["/images/Product/pro-4.png"],
    name: "Rhino 69 10000K",
    category: "Dietary Supplement",
    quote: "Discover the potential",
    price: 12,
    offer: 2,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Cone Paper",
    createdBy: "Munna",
    updatedAt: "01/04/2023",
  },
  {
    id: 111,
    image: ["/images/Product/pro-3.png"],
    name: "Rhino 69 2400K",
    category: "VIP Royal Honey",
    quote: "Honey for Extra Energy",
    price: 10,
    offer: "hot",
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Cone Paper",
    createdBy: "Munna",
    updatedAt: "01/04/2023",
  },
  {
    id: 112,
    image: ["/images/Product/pro-1.png"],
    name: "Rhino 69 600K",
    category: "Male enhancement Supplement",
    quote: "Don't Quit ... ",
    price: 100,
    offer: 5,
    quantity: 1,
    description:
      "Make the intimate moments with your partner last longer and feel better.",
    reviews: "4.5 reviews",
    category: "Cone Paper",
    createdBy: "Munna",
    updatedAt: "02/04/2023",
  },
];
export const getProductById = (id) => {
  return allProducts.find((product) => product.id === Number(id));
};

export const getProductByCategoryName = (category) => {
  const categoryName = category.split(" ");
};
