export const peoplesReview = [
  {
    id: 1,
    star: 4,
    productName: "Royal Honey For Men – Gold (12 Sachets – 20 G)",
    comment: "Great. Gave me the boost that I needed",
    customer: "Dan Benthall",
    createdBy: "5/12/23",
    image: ["/Honey/Royal Honey VIP/Royal Honey VIP.jpeg"],
  },
  {
    id: 2,
    star: 5,
    productName: "Royal Honey VIP 22g Pouches",
    comment:
      "I like it.I was very strong that night ,very hard and too long to cumshot I feel erect too long and too long to cumshot.Thank shop",
    customer: "Maurice Hunt",
    createdBy: "8/12/23",
    image: ["/Honey/Royal Honey VIP/RoYAL hONEY.jpeg"],
  },
  {
    id: 3,
    star: 3,
    productName: "Etumax Honey 20g Sachet",
    comment:
      "Everyone loves it Works fast last long and delivers good price and quick",
    customer: "Rock hard",
    createdBy: "5/7/23",
    image: ["/Honey/Etumax Honey/Etumax(4).jpeg"],
  },
  {
    id: 4,
    star: 4,
    productName: "Red Bull Honey 22g Pouches",
    comment: "Great. Gave me the boost that I needed",
    customer: "Cole DeCant",
    createdBy: "5/12/23",
    image: ["/Honey/Red Bull Honey/Red Bull Honey.jpeg"],
  },
  {
    id: 5,
    star: 5,
    productName: "Vitamax Double Shot 20g Sachet",
    comment: "Great. Gave me the boost that I needed",
    customer: "Cole DeCant",
    createdBy: "5/12/23",
    image: ["/Honey/Vitamax Double shot/Vitamax Double shot.jpeg"],
  },
  {
    id: 6,
    star: 4,
    productName: "Rhino Platinum Liquid Shot",
    comment: "Great. Gave me the boost that I needed",
    customer: "Hieu Nguyen",
    createdBy: "5/12/23",
    image: ["/Pills/Rhino-69-1200k/Rhino-69-1200k-Front-Side.png"],
  },
  {
    id: 7,
    star: 3,
    productName: "Rhino 100k Gold",
    comment: "Great. Gave me the boost that I needed",
    customer: "Robert Harris",
    createdBy: "5/12/23",
    image: ["/Pills//100k-Gold/100k-Gold-Front-Side.png"],
  },
  {
    id: 8,
    star: 4,
    productName: "Zesus-250k",
    comment: "Great. Gave me the boost that I needed",
    customer: "Larry T",
    createdBy: "5/12/23",
    image: ["/Pills/Zesus-250k/Zesus-250k-Front-Side.png"],
  },
  {
    id: 9,
    star: 5,
    productName: "RAW 32 11/4 Classic Cones",
    comment: "Great. Gave me the boost that I needed",
    customer: "Hieu Nguyen",
    createdBy: "5/12/23",
    image: ["/Cannabies Accessories/6.png"],
  },
  {
    id: 10,
    star: 3,
    productName: "Rhino 69 600K",
    comment: "Great. Gave me the boost that I needed",
    customer: "Harry",
    createdBy: "5/12/23",
    image: ["/images/Product/pro-1.png"],
  },
];
