export const FAVORITE_ACTION_TYPE = {
  SET_ITEM_TO_FAVORITE: "favorite/SET_ITEM_TO_FAVORITE",
  SET_FAVORITE_COUNT: "favorite/SET_FAVORITE_COUNT",
  SET_FAVORITE_EXIST: "favorite/SET_FAVORITE_EXIST",
};
