export const ORDER_ACTION_TYPE = {
  ADD_ITEM_TO_ORDER_LIST: "order/ADD_ITEM_TO_ORDER_LIST",
  UPDATE_SHIPPING_ADDRESS: "order/UPDATE_SHIPPING_ADDRESS",
  UPDATE_BILLING_ADDRESS: "order/UPDATE_BILLING_ADDRESS",
  UPDATE_PAYMENT: "order/UPDATE_PAYMENT",
  UPDATE_STATUS: "order/UPDATE_STATUS",
};
